/**
 *
 *  Attachments.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace messenger_db
{

class Attachments
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _message_id;
        static const std::string _post_id;
        static const std::string _file_type;
        static const std::string _file_size;
        static const std::string _file_path;
        static const std::string _uploaded_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Attachments(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Attachments(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Attachments(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Attachments() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column message_id  */
    ///Get the value of the column message_id, returns the default value if the column is null
    const int64_t &getValueOfMessageId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getMessageId() const noexcept;
    ///Set the value of the column message_id
    void setMessageId(const int64_t &pMessageId) noexcept;
    void setMessageIdToNull() noexcept;

    /**  For column post_id  */
    ///Get the value of the column post_id, returns the default value if the column is null
    const int64_t &getValueOfPostId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getPostId() const noexcept;
    ///Set the value of the column post_id
    void setPostId(const int64_t &pPostId) noexcept;
    void setPostIdToNull() noexcept;

    /**  For column file_type  */
    ///Get the value of the column file_type, returns the default value if the column is null
    const std::string &getValueOfFileType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFileType() const noexcept;
    ///Set the value of the column file_type
    void setFileType(const std::string &pFileType) noexcept;
    void setFileType(std::string &&pFileType) noexcept;

    /**  For column file_size  */
    ///Get the value of the column file_size, returns the default value if the column is null
    const int64_t &getValueOfFileSize() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getFileSize() const noexcept;
    ///Set the value of the column file_size
    void setFileSize(const int64_t &pFileSize) noexcept;

    /**  For column file_path  */
    ///Get the value of the column file_path, returns the default value if the column is null
    const std::string &getValueOfFilePath() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFilePath() const noexcept;
    ///Set the value of the column file_path
    void setFilePath(const std::string &pFilePath) noexcept;
    void setFilePath(std::string &&pFilePath) noexcept;

    /**  For column uploaded_at  */
    ///Get the value of the column uploaded_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUploadedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUploadedAt() const noexcept;
    ///Set the value of the column uploaded_at
    void setUploadedAt(const ::trantor::Date &pUploadedAt) noexcept;
    void setUploadedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 7;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Attachments>;
    friend drogon::orm::BaseBuilder<Attachments, true, true>;
    friend drogon::orm::BaseBuilder<Attachments, true, false>;
    friend drogon::orm::BaseBuilder<Attachments, false, true>;
    friend drogon::orm::BaseBuilder<Attachments, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Attachments>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int64_t> messageId_;
    std::shared_ptr<int64_t> postId_;
    std::shared_ptr<std::string> fileType_;
    std::shared_ptr<int64_t> fileSize_;
    std::shared_ptr<std::string> filePath_;
    std::shared_ptr<::trantor::Date> uploadedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[7]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "message_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "post_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "file_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "file_size,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "file_path,";
            ++parametersCount;
        }
        sql += "uploaded_at,";
        ++parametersCount;
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace messenger_db
} // namespace drogon_model
