/**
 *
 *  Messages.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace messenger_db
{

class Messages
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _chat_id;
        static const std::string _sender_id;
        static const std::string _reply_to_message_id;
        static const std::string _forwarded_from_user_id;
        static const std::string _forwarded_from_user_name;
        static const std::string _text;
        static const std::string _sent_at;
        static const std::string _edited_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Messages(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Messages(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Messages(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Messages() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column chat_id  */
    ///Get the value of the column chat_id, returns the default value if the column is null
    const int64_t &getValueOfChatId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getChatId() const noexcept;
    ///Set the value of the column chat_id
    void setChatId(const int64_t &pChatId) noexcept;

    /**  For column sender_id  */
    ///Get the value of the column sender_id, returns the default value if the column is null
    const int64_t &getValueOfSenderId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getSenderId() const noexcept;
    ///Set the value of the column sender_id
    void setSenderId(const int64_t &pSenderId) noexcept;
    void setSenderIdToNull() noexcept;

    /**  For column reply_to_message_id  */
    ///Get the value of the column reply_to_message_id, returns the default value if the column is null
    const int64_t &getValueOfReplyToMessageId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getReplyToMessageId() const noexcept;
    ///Set the value of the column reply_to_message_id
    void setReplyToMessageId(const int64_t &pReplyToMessageId) noexcept;
    void setReplyToMessageIdToNull() noexcept;

    /**  For column forwarded_from_user_id  */
    ///Get the value of the column forwarded_from_user_id, returns the default value if the column is null
    const int64_t &getValueOfForwardedFromUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getForwardedFromUserId() const noexcept;
    ///Set the value of the column forwarded_from_user_id
    void setForwardedFromUserId(const int64_t &pForwardedFromUserId) noexcept;
    void setForwardedFromUserIdToNull() noexcept;

    /**  For column forwarded_from_user_name  */
    ///Get the value of the column forwarded_from_user_name, returns the default value if the column is null
    const std::string &getValueOfForwardedFromUserName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getForwardedFromUserName() const noexcept;
    ///Set the value of the column forwarded_from_user_name
    void setForwardedFromUserName(const std::string &pForwardedFromUserName) noexcept;
    void setForwardedFromUserName(std::string &&pForwardedFromUserName) noexcept;
    void setForwardedFromUserNameToNull() noexcept;

    /**  For column text  */
    ///Get the value of the column text, returns the default value if the column is null
    const std::string &getValueOfText() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getText() const noexcept;
    ///Set the value of the column text
    void setText(const std::string &pText) noexcept;
    void setText(std::string &&pText) noexcept;

    /**  For column sent_at  */
    ///Get the value of the column sent_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfSentAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getSentAt() const noexcept;
    ///Set the value of the column sent_at
    void setSentAt(const ::trantor::Date &pSentAt) noexcept;
    void setSentAtToNull() noexcept;

    /**  For column edited_at  */
    ///Get the value of the column edited_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfEditedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getEditedAt() const noexcept;
    ///Set the value of the column edited_at
    void setEditedAt(const ::trantor::Date &pEditedAt) noexcept;
    void setEditedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Messages>;
    friend drogon::orm::BaseBuilder<Messages, true, true>;
    friend drogon::orm::BaseBuilder<Messages, true, false>;
    friend drogon::orm::BaseBuilder<Messages, false, true>;
    friend drogon::orm::BaseBuilder<Messages, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Messages>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int64_t> chatId_;
    std::shared_ptr<int64_t> senderId_;
    std::shared_ptr<int64_t> replyToMessageId_;
    std::shared_ptr<int64_t> forwardedFromUserId_;
    std::shared_ptr<std::string> forwardedFromUserName_;
    std::shared_ptr<std::string> text_;
    std::shared_ptr<::trantor::Date> sentAt_;
    std::shared_ptr<::trantor::Date> editedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "chat_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "sender_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "reply_to_message_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "forwarded_from_user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "forwarded_from_user_name,";
            ++parametersCount;
        }
        sql += "text,";
        ++parametersCount;
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        sql += "sent_at,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        if(dirtyFlag_[8])
        {
            sql += "edited_at,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace messenger_db
} // namespace drogon_model
