/**
 *
 *  Messages.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Messages.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::messenger_db;

const std::string Messages::Cols::_id = "\"id\"";
const std::string Messages::Cols::_chat_id = "\"chat_id\"";
const std::string Messages::Cols::_sender_id = "\"sender_id\"";
const std::string Messages::Cols::_reply_to_message_id = "\"reply_to_message_id\"";
const std::string Messages::Cols::_forwarded_from_user_id = "\"forwarded_from_user_id\"";
const std::string Messages::Cols::_forwarded_from_user_name = "\"forwarded_from_user_name\"";
const std::string Messages::Cols::_text = "\"text\"";
const std::string Messages::Cols::_sent_at = "\"sent_at\"";
const std::string Messages::Cols::_edited_at = "\"edited_at\"";
const std::string Messages::primaryKeyName = "id";
const bool Messages::hasPrimaryKey = true;
const std::string Messages::tableName = "\"messages\"";

const std::vector<typename Messages::MetaData> Messages::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"chat_id","int64_t","bigint",8,0,0,1},
{"sender_id","int64_t","bigint",8,0,0,0},
{"reply_to_message_id","int64_t","bigint",8,0,0,0},
{"forwarded_from_user_id","int64_t","bigint",8,0,0,0},
{"forwarded_from_user_name","std::string","character varying",100,0,0,0},
{"text","std::string","text",0,0,0,1},
{"sent_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"edited_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &Messages::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Messages::Messages(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["chat_id"].isNull())
        {
            chatId_=std::make_shared<int64_t>(r["chat_id"].as<int64_t>());
        }
        if(!r["sender_id"].isNull())
        {
            senderId_=std::make_shared<int64_t>(r["sender_id"].as<int64_t>());
        }
        if(!r["reply_to_message_id"].isNull())
        {
            replyToMessageId_=std::make_shared<int64_t>(r["reply_to_message_id"].as<int64_t>());
        }
        if(!r["forwarded_from_user_id"].isNull())
        {
            forwardedFromUserId_=std::make_shared<int64_t>(r["forwarded_from_user_id"].as<int64_t>());
        }
        if(!r["forwarded_from_user_name"].isNull())
        {
            forwardedFromUserName_=std::make_shared<std::string>(r["forwarded_from_user_name"].as<std::string>());
        }
        if(!r["text"].isNull())
        {
            text_=std::make_shared<std::string>(r["text"].as<std::string>());
        }
        if(!r["sent_at"].isNull())
        {
            auto timeStr = r["sent_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                sentAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["edited_at"].isNull())
        {
            auto timeStr = r["edited_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                editedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            chatId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            senderId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            replyToMessageId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            forwardedFromUserId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            forwardedFromUserName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            text_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                sentAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                editedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Messages::Messages(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            chatId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            senderId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            replyToMessageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            forwardedFromUserId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            forwardedFromUserName_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            text_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                sentAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                editedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Messages::Messages(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("chat_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["chat_id"].isNull())
        {
            chatId_=std::make_shared<int64_t>((int64_t)pJson["chat_id"].asInt64());
        }
    }
    if(pJson.isMember("sender_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["sender_id"].isNull())
        {
            senderId_=std::make_shared<int64_t>((int64_t)pJson["sender_id"].asInt64());
        }
    }
    if(pJson.isMember("reply_to_message_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["reply_to_message_id"].isNull())
        {
            replyToMessageId_=std::make_shared<int64_t>((int64_t)pJson["reply_to_message_id"].asInt64());
        }
    }
    if(pJson.isMember("forwarded_from_user_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["forwarded_from_user_id"].isNull())
        {
            forwardedFromUserId_=std::make_shared<int64_t>((int64_t)pJson["forwarded_from_user_id"].asInt64());
        }
    }
    if(pJson.isMember("forwarded_from_user_name"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["forwarded_from_user_name"].isNull())
        {
            forwardedFromUserName_=std::make_shared<std::string>(pJson["forwarded_from_user_name"].asString());
        }
    }
    if(pJson.isMember("text"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["text"].isNull())
        {
            text_=std::make_shared<std::string>(pJson["text"].asString());
        }
    }
    if(pJson.isMember("sent_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["sent_at"].isNull())
        {
            auto timeStr = pJson["sent_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                sentAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("edited_at"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["edited_at"].isNull())
        {
            auto timeStr = pJson["edited_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                editedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Messages::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            chatId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            senderId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            replyToMessageId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            forwardedFromUserId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            forwardedFromUserName_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            text_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                sentAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                editedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Messages::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("chat_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["chat_id"].isNull())
        {
            chatId_=std::make_shared<int64_t>((int64_t)pJson["chat_id"].asInt64());
        }
    }
    if(pJson.isMember("sender_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["sender_id"].isNull())
        {
            senderId_=std::make_shared<int64_t>((int64_t)pJson["sender_id"].asInt64());
        }
    }
    if(pJson.isMember("reply_to_message_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["reply_to_message_id"].isNull())
        {
            replyToMessageId_=std::make_shared<int64_t>((int64_t)pJson["reply_to_message_id"].asInt64());
        }
    }
    if(pJson.isMember("forwarded_from_user_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["forwarded_from_user_id"].isNull())
        {
            forwardedFromUserId_=std::make_shared<int64_t>((int64_t)pJson["forwarded_from_user_id"].asInt64());
        }
    }
    if(pJson.isMember("forwarded_from_user_name"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["forwarded_from_user_name"].isNull())
        {
            forwardedFromUserName_=std::make_shared<std::string>(pJson["forwarded_from_user_name"].asString());
        }
    }
    if(pJson.isMember("text"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["text"].isNull())
        {
            text_=std::make_shared<std::string>(pJson["text"].asString());
        }
    }
    if(pJson.isMember("sent_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["sent_at"].isNull())
        {
            auto timeStr = pJson["sent_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                sentAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("edited_at"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["edited_at"].isNull())
        {
            auto timeStr = pJson["edited_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                editedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &Messages::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Messages::getId() const noexcept
{
    return id_;
}
void Messages::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Messages::PrimaryKeyType & Messages::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &Messages::getValueOfChatId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(chatId_)
        return *chatId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Messages::getChatId() const noexcept
{
    return chatId_;
}
void Messages::setChatId(const int64_t &pChatId) noexcept
{
    chatId_ = std::make_shared<int64_t>(pChatId);
    dirtyFlag_[1] = true;
}

const int64_t &Messages::getValueOfSenderId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(senderId_)
        return *senderId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Messages::getSenderId() const noexcept
{
    return senderId_;
}
void Messages::setSenderId(const int64_t &pSenderId) noexcept
{
    senderId_ = std::make_shared<int64_t>(pSenderId);
    dirtyFlag_[2] = true;
}
void Messages::setSenderIdToNull() noexcept
{
    senderId_.reset();
    dirtyFlag_[2] = true;
}

const int64_t &Messages::getValueOfReplyToMessageId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(replyToMessageId_)
        return *replyToMessageId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Messages::getReplyToMessageId() const noexcept
{
    return replyToMessageId_;
}
void Messages::setReplyToMessageId(const int64_t &pReplyToMessageId) noexcept
{
    replyToMessageId_ = std::make_shared<int64_t>(pReplyToMessageId);
    dirtyFlag_[3] = true;
}
void Messages::setReplyToMessageIdToNull() noexcept
{
    replyToMessageId_.reset();
    dirtyFlag_[3] = true;
}

const int64_t &Messages::getValueOfForwardedFromUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(forwardedFromUserId_)
        return *forwardedFromUserId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Messages::getForwardedFromUserId() const noexcept
{
    return forwardedFromUserId_;
}
void Messages::setForwardedFromUserId(const int64_t &pForwardedFromUserId) noexcept
{
    forwardedFromUserId_ = std::make_shared<int64_t>(pForwardedFromUserId);
    dirtyFlag_[4] = true;
}
void Messages::setForwardedFromUserIdToNull() noexcept
{
    forwardedFromUserId_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Messages::getValueOfForwardedFromUserName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(forwardedFromUserName_)
        return *forwardedFromUserName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Messages::getForwardedFromUserName() const noexcept
{
    return forwardedFromUserName_;
}
void Messages::setForwardedFromUserName(const std::string &pForwardedFromUserName) noexcept
{
    forwardedFromUserName_ = std::make_shared<std::string>(pForwardedFromUserName);
    dirtyFlag_[5] = true;
}
void Messages::setForwardedFromUserName(std::string &&pForwardedFromUserName) noexcept
{
    forwardedFromUserName_ = std::make_shared<std::string>(std::move(pForwardedFromUserName));
    dirtyFlag_[5] = true;
}
void Messages::setForwardedFromUserNameToNull() noexcept
{
    forwardedFromUserName_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Messages::getValueOfText() const noexcept
{
    static const std::string defaultValue = std::string();
    if(text_)
        return *text_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Messages::getText() const noexcept
{
    return text_;
}
void Messages::setText(const std::string &pText) noexcept
{
    text_ = std::make_shared<std::string>(pText);
    dirtyFlag_[6] = true;
}
void Messages::setText(std::string &&pText) noexcept
{
    text_ = std::make_shared<std::string>(std::move(pText));
    dirtyFlag_[6] = true;
}

const ::trantor::Date &Messages::getValueOfSentAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(sentAt_)
        return *sentAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Messages::getSentAt() const noexcept
{
    return sentAt_;
}
void Messages::setSentAt(const ::trantor::Date &pSentAt) noexcept
{
    sentAt_ = std::make_shared<::trantor::Date>(pSentAt);
    dirtyFlag_[7] = true;
}
void Messages::setSentAtToNull() noexcept
{
    sentAt_.reset();
    dirtyFlag_[7] = true;
}

const ::trantor::Date &Messages::getValueOfEditedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(editedAt_)
        return *editedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Messages::getEditedAt() const noexcept
{
    return editedAt_;
}
void Messages::setEditedAt(const ::trantor::Date &pEditedAt) noexcept
{
    editedAt_ = std::make_shared<::trantor::Date>(pEditedAt);
    dirtyFlag_[8] = true;
}
void Messages::setEditedAtToNull() noexcept
{
    editedAt_.reset();
    dirtyFlag_[8] = true;
}

void Messages::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Messages::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "chat_id",
        "sender_id",
        "reply_to_message_id",
        "forwarded_from_user_id",
        "forwarded_from_user_name",
        "text",
        "sent_at",
        "edited_at"
    };
    return inCols;
}

void Messages::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getChatId())
        {
            binder << getValueOfChatId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSenderId())
        {
            binder << getValueOfSenderId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getReplyToMessageId())
        {
            binder << getValueOfReplyToMessageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getForwardedFromUserId())
        {
            binder << getValueOfForwardedFromUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getForwardedFromUserName())
        {
            binder << getValueOfForwardedFromUserName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getText())
        {
            binder << getValueOfText();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSentAt())
        {
            binder << getValueOfSentAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getEditedAt())
        {
            binder << getValueOfEditedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Messages::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Messages::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getChatId())
        {
            binder << getValueOfChatId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getSenderId())
        {
            binder << getValueOfSenderId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getReplyToMessageId())
        {
            binder << getValueOfReplyToMessageId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getForwardedFromUserId())
        {
            binder << getValueOfForwardedFromUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getForwardedFromUserName())
        {
            binder << getValueOfForwardedFromUserName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getText())
        {
            binder << getValueOfText();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSentAt())
        {
            binder << getValueOfSentAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getEditedAt())
        {
            binder << getValueOfEditedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Messages::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getChatId())
    {
        ret["chat_id"]=(Json::Int64)getValueOfChatId();
    }
    else
    {
        ret["chat_id"]=Json::Value();
    }
    if(getSenderId())
    {
        ret["sender_id"]=(Json::Int64)getValueOfSenderId();
    }
    else
    {
        ret["sender_id"]=Json::Value();
    }
    if(getReplyToMessageId())
    {
        ret["reply_to_message_id"]=(Json::Int64)getValueOfReplyToMessageId();
    }
    else
    {
        ret["reply_to_message_id"]=Json::Value();
    }
    if(getForwardedFromUserId())
    {
        ret["forwarded_from_user_id"]=(Json::Int64)getValueOfForwardedFromUserId();
    }
    else
    {
        ret["forwarded_from_user_id"]=Json::Value();
    }
    if(getForwardedFromUserName())
    {
        ret["forwarded_from_user_name"]=getValueOfForwardedFromUserName();
    }
    else
    {
        ret["forwarded_from_user_name"]=Json::Value();
    }
    if(getText())
    {
        ret["text"]=getValueOfText();
    }
    else
    {
        ret["text"]=Json::Value();
    }
    if(getSentAt())
    {
        ret["sent_at"]=getSentAt()->toDbStringLocal();
    }
    else
    {
        ret["sent_at"]=Json::Value();
    }
    if(getEditedAt())
    {
        ret["edited_at"]=getEditedAt()->toDbStringLocal();
    }
    else
    {
        ret["edited_at"]=Json::Value();
    }
    return ret;
}

std::string Messages::toString() const
{
    return toJson().toStyledString();
}

Json::Value Messages::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getChatId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfChatId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getSenderId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfSenderId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getReplyToMessageId())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfReplyToMessageId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getForwardedFromUserId())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfForwardedFromUserId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getForwardedFromUserName())
            {
                ret[pMasqueradingVector[5]]=getValueOfForwardedFromUserName();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getText())
            {
                ret[pMasqueradingVector[6]]=getValueOfText();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getSentAt())
            {
                ret[pMasqueradingVector[7]]=getSentAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getEditedAt())
            {
                ret[pMasqueradingVector[8]]=getEditedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getChatId())
    {
        ret["chat_id"]=(Json::Int64)getValueOfChatId();
    }
    else
    {
        ret["chat_id"]=Json::Value();
    }
    if(getSenderId())
    {
        ret["sender_id"]=(Json::Int64)getValueOfSenderId();
    }
    else
    {
        ret["sender_id"]=Json::Value();
    }
    if(getReplyToMessageId())
    {
        ret["reply_to_message_id"]=(Json::Int64)getValueOfReplyToMessageId();
    }
    else
    {
        ret["reply_to_message_id"]=Json::Value();
    }
    if(getForwardedFromUserId())
    {
        ret["forwarded_from_user_id"]=(Json::Int64)getValueOfForwardedFromUserId();
    }
    else
    {
        ret["forwarded_from_user_id"]=Json::Value();
    }
    if(getForwardedFromUserName())
    {
        ret["forwarded_from_user_name"]=getValueOfForwardedFromUserName();
    }
    else
    {
        ret["forwarded_from_user_name"]=Json::Value();
    }
    if(getText())
    {
        ret["text"]=getValueOfText();
    }
    else
    {
        ret["text"]=Json::Value();
    }
    if(getSentAt())
    {
        ret["sent_at"]=getSentAt()->toDbStringLocal();
    }
    else
    {
        ret["sent_at"]=Json::Value();
    }
    if(getEditedAt())
    {
        ret["edited_at"]=getEditedAt()->toDbStringLocal();
    }
    else
    {
        ret["edited_at"]=Json::Value();
    }
    return ret;
}

bool Messages::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("chat_id"))
    {
        if(!validJsonOfField(1, "chat_id", pJson["chat_id"], err, true))
            return false;
    }
    else
    {
        err="The chat_id column cannot be null";
        return false;
    }
    if(pJson.isMember("sender_id"))
    {
        if(!validJsonOfField(2, "sender_id", pJson["sender_id"], err, true))
            return false;
    }
    if(pJson.isMember("reply_to_message_id"))
    {
        if(!validJsonOfField(3, "reply_to_message_id", pJson["reply_to_message_id"], err, true))
            return false;
    }
    if(pJson.isMember("forwarded_from_user_id"))
    {
        if(!validJsonOfField(4, "forwarded_from_user_id", pJson["forwarded_from_user_id"], err, true))
            return false;
    }
    if(pJson.isMember("forwarded_from_user_name"))
    {
        if(!validJsonOfField(5, "forwarded_from_user_name", pJson["forwarded_from_user_name"], err, true))
            return false;
    }
    if(pJson.isMember("text"))
    {
        if(!validJsonOfField(6, "text", pJson["text"], err, true))
            return false;
    }
    if(pJson.isMember("sent_at"))
    {
        if(!validJsonOfField(7, "sent_at", pJson["sent_at"], err, true))
            return false;
    }
    if(pJson.isMember("edited_at"))
    {
        if(!validJsonOfField(8, "edited_at", pJson["edited_at"], err, true))
            return false;
    }
    return true;
}
bool Messages::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Messages::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("chat_id"))
    {
        if(!validJsonOfField(1, "chat_id", pJson["chat_id"], err, false))
            return false;
    }
    if(pJson.isMember("sender_id"))
    {
        if(!validJsonOfField(2, "sender_id", pJson["sender_id"], err, false))
            return false;
    }
    if(pJson.isMember("reply_to_message_id"))
    {
        if(!validJsonOfField(3, "reply_to_message_id", pJson["reply_to_message_id"], err, false))
            return false;
    }
    if(pJson.isMember("forwarded_from_user_id"))
    {
        if(!validJsonOfField(4, "forwarded_from_user_id", pJson["forwarded_from_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("forwarded_from_user_name"))
    {
        if(!validJsonOfField(5, "forwarded_from_user_name", pJson["forwarded_from_user_name"], err, false))
            return false;
    }
    if(pJson.isMember("text"))
    {
        if(!validJsonOfField(6, "text", pJson["text"], err, false))
            return false;
    }
    if(pJson.isMember("sent_at"))
    {
        if(!validJsonOfField(7, "sent_at", pJson["sent_at"], err, false))
            return false;
    }
    if(pJson.isMember("edited_at"))
    {
        if(!validJsonOfField(8, "edited_at", pJson["edited_at"], err, false))
            return false;
    }
    return true;
}
bool Messages::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Messages::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
